package com.thepyprogrammer.phykt.unit


val dm = Unit("m", "decimetre", "length", 0.1)
val ds = Unit("s", "decisecond", "time", 0.1, isScalar=true)
val dg = Unit("g", "decigram", "mass", 0.1/1000, isScalar=true)

val dA = Unit("A", "deciampere", "electric current", 0.1, isScalar=true)
val dK = Unit("K", "decikelvin", "thermodynamic temperature", 0.1, isScalar=true)
val dmol = Unit("mol", "decimole", "amount of substance", 0.1, isScalar=true)
val dcd = Unit("cd", "decicandela", "luminous intensity", 0.1, isScalar=true)
val dHz = Unit("1.0/s", "decihertz", "frequency", 0.1, isScalar=true)
val dN = Unit("gm/s^2", "decinewton", "force", 0.1)
val dPa = Unit("g/ms^2", "decipascal", "pressure, stress", 0.1, isScalar=true)
val dJ = Unit("gm^2/s^2", "decijoule", "energy, work, amount of heat", 0.1, isScalar=true)
val dW = Unit("gm^2/s^3", "deciwatt", "power, radiant flux", 0.1, isScalar=true)
val dC = Unit("As", "decicoulomb", "electric charge, quantity of electricity", 0.1, isScalar=true)
val dV = Unit("gm^2/As^3", "decivolt", "electric potential, emf", 0.1, isScalar=true)
val dΩ = Unit("gm^2/s^3A^2", "deciohm", "electric resistance, impedance", 0.1, isScalar=true)
val dohm = Unit("gm^2/s^3A^2", "deciohm", "electric resistance, impedance", 0.1, isScalar=true)
val dkat = Unit("mol/s", "decikatal", "catalytic activity", 0.1, isScalar=true)
val dS = Unit("A^2s^3/gm^2", "decisiemen", "electric conductance", 0.1, isScalar=true)
val dF = Unit("A^2s^4/gm^2", "decifarad", "capacitance", 0.1, isScalar=true)
val dWb = Unit("gm^2/As^2", "deciweber", "magnetic flux", 0.1, isScalar=true)
val dT = Unit("g/As^2", "decitesla", "magnetic field", 0.1)
val dH = Unit("gm^2/A^2s^2", "decihenry", "inductance", 0.1, isScalar=true)
val ddegreeCelsius = Unit("K", "deci°Celsius", "temperature on the celsius scale", 0.1, -273.15, isScalar=true)
val ddegCelsius = Unit("K", "deci°Celsius", "temperature on the celsius scale", 0.1, -273.15, isScalar=true)
val ddegC = Unit("K", "deci°Celsius", "temperature on the celsius scale", 0.1, -273.15, isScalar=true)
val dGy = Unit("m^2/s^2", "decigray", "absorbed dose, specific energy", 0.1, isScalar=true)
val dSv = Unit("m^2/s^2", "decisievert", "dose equivalent(d)", 0.1, isScalar=true)
val dBq = Unit("1.0/s", "decibecquerel", "activity (of a radionuclide)", 0.1, isScalar=true)
val dlm = Unit("cd", "decilumen", "luminous flux", 0.1, isScalar=true)
val dlx = Unit("cd/m^2", "decilux", "illuminance", 0.1, isScalar=true)
val deV = Unit("gm^2/s^2", "decielectron Volts", "measure of energy", 0.1*1.60217648740e-19, isScalar=true)
val dly = Unit("m", "decilightyear", "measure of distance", 0.1*3600*24*365.25*299792458)
val dpc = Unit("m", "deciparsec", "measure of distance", 0.1*3.086e16, isScalar=true)
val dL = Unit("m^3", "decilitre", "measure of volume", 0.1/1000, isScalar=true)
