package com.thepyprogrammer.phykt.unit

val dam = Unit("m", "dekametre", "length", 10.0)
val das = Unit("s", "dekasecond", "time", 10.0, isScalar=true)
val dag = Unit("g", "dekagram", "mass", 0.01, isScalar=true)
val daA = Unit("A", "dekaampere", "electric current", 10.0, isScalar=true)
val daK = Unit("K", "dekakelvin", "thermodynamic temperature", 10.0, isScalar=true)
val damol = Unit("mol", "dekamole", "amount of substance", 10.0, isScalar=true)
val dacd = Unit("cd", "dekacandela", "luminous intensity", 10.0, isScalar=true)
val daHz = Unit("1.0/s", "dekahertz", "frequency", 10.0, isScalar=true)
val daN = Unit("gm/s^2", "dekanewton", "force", 10.0)
val daPa = Unit("g/ms^2", "dekapascal", "pressure, stress", 10.0, isScalar=true)
val daJ = Unit("gm^2/s^2", "dekajoule", "energy, work, amount of heat", 10.0, isScalar=true)
val daW = Unit("gm^2/s^3", "dekawatt", "power, radiant flux", 10.0, isScalar=true)
val daC = Unit("As", "dekacoulomb", "electric charge, quantity of electricity", 10.0, isScalar=true)
val daV = Unit("gm^2/As^3", "dekavolt", "electric potential, emf", 10.0, isScalar=true)
val daΩ = Unit("gm^2/s^3A^2", "dekaohm", "electric resistance, impedance", 10.0, isScalar=true)
val daohm = Unit("gm^2/s^3A^2", "dekaohm", "electric resistance, impedance", 10.0, isScalar=true)
val dakat = Unit("mol/s", "dekakatal", "catalytic activity", 10.0, isScalar=true)
val daS = Unit("A^2s^3/gm^2", "dekasiemen", "electric conductance", 10.0, isScalar=true)
val daF = Unit("A^2s^4/gm^2", "dekafarad", "capacitance", 10.0, isScalar=true)
val daWb = Unit("gm^2/As^2", "dekaweber", "magnetic flux", 10.0, isScalar=true)
val daT = Unit("g/As^2", "dekatesla", "magnetic field", 10.0)
val daH = Unit("gm^2/A^2s^2", "dekahenry", "inductance", 10.0, isScalar=true)
val dadegreeCelsius = Unit("K", "deka°Celsius", "temperature on the celsius scale", 10.0, -273.15, isScalar=true)
val dadegCelsius = Unit("K", "deka°Celsius", "temperature on the celsius scale", 10.0, -273.15, isScalar=true)
val dadegC = Unit("K", "deka°Celsius", "temperature on the celsius scale", 10.0, -273.15, isScalar=true)
val daGy = Unit("m^2/s^2", "dekagray", "absorbed dose, specific energy", 10.0, isScalar=true)
val daSv = Unit("m^2/s^2", "dekasievert", "dose equivalent(d)", 10.0, isScalar=true)
val daBq = Unit("1.0/s", "dekabecquerel", "activity (of a radionuclide)", 10.0, isScalar=true)
val dalm = Unit("cd", "dekalumen", "luminous flux", 10.0, isScalar=true)
val dalx = Unit("cd/m^2", "dekalux", "illuminance", 10.0, isScalar=true)
val daeV = Unit("gm^2/s^2", "dekaelectron Volts", "measure of energy", 10.0*1.60217648740e-19, isScalar=true)
val daly = Unit("m", "dekalightyear", "measure of distance", 10.0*3600*24*365.25*299792458)
val dapc = Unit("m", "dekaparsec", "measure of distance", 10.0*3.086e16, isScalar=true)
val daL = Unit("m^3", "dekalitre", "measure of volume", 10.0/1000, isScalar=true)

