package com.thepyprogrammer.phykt.unit

val Em = Unit("m", "Exametre", "length", 1e+18)
val Es = Unit("s", "Exasecond", "time", 1e+18, isScalar=true)
val Eg = Unit("g", "Exagram", "mass", 1e+18 / 1000, isScalar=true)
val EA = Unit("A", "Exaampere", "electric current", 1e+18, isScalar=true)
val EK = Unit("K", "Exakelvin", "thermodynamic temperature", 1e+18, isScalar=true)
val Emol = Unit("mol", "Examole", "amount of substance", 1e+18, isScalar=true)
val Ecd = Unit("cd", "Exacandela", "luminous intensity", 1e+18, isScalar=true)
val EHz = Unit("1.0/s", "Exahertz", "frequency", 1e+18, isScalar=true)
val EN = Unit("gm/s^2", "Exanewton", "force", 1e+18)
val EPa = Unit("g/ms^2", "Exapascal", "pressure, stress", 1e+18, isScalar=true)
val EJ = Unit("gm^2/s^2", "Exajoule", "energy, work, amount of heat", 1e+18, isScalar=true)
val EW = Unit("gm^2/s^3", "Exawatt", "power, radiant flux", 1e+18, isScalar=true)
val EC = Unit("As", "Exacoulomb", "electric charge, quantity of electricity", 1e+18, isScalar=true)
val EV = Unit("gm^2/As^3", "Exavolt", "electric potential, emf", 1e+18, isScalar=true)
val EΩ = Unit("gm^2/s^3A^2", "Exaohm", "electric resistance, impedance", 1e+18, isScalar=true)
val Eohm = Unit("gm^2/s^3A^2", "Exaohm", "electric resistance, impedance", 1e+18, isScalar=true)
val Ekat = Unit("mol/s", "Exakatal", "catalytic activity", 1e+18, isScalar=true)
val ES = Unit("A^2s^3/gm^2", "Exasiemen", "electric conductance", 1e+18, isScalar=true)
val EF = Unit("A^2s^4/gm^2", "Exafarad", "capacitance", 1e+18, isScalar=true)
val EWb = Unit("gm^2/As^2", "Exaweber", "magnetic flux", 1e+18, isScalar=true)
val ET = Unit("g/As^2", "Exatesla", "magnetic field", 1e+18)
val EH = Unit("gm^2/A^2s^2", "Exahenry", "inductance", 1e+18, isScalar=true)
val EdegreeCelsius = Unit("K", "Exa°Celsius", "temperature on the celsius scale", 1e+18, -273.15, isScalar=true)
val EdegCelsius = Unit("K", "Exa°Celsius", "temperature on the celsius scale", 1e+18, -273.15, isScalar=true)
val EdegC = Unit("K", "Exa°Celsius", "temperature on the celsius scale", 1e+18, -273.15, isScalar=true)
val EGy = Unit("m^2/s^2", "Exagray", "absorbed dose, specific energy", 1e+18, isScalar=true)
val ESv = Unit("m^2/s^2", "Exasievert", "dose equivalent(d)", 1e+18, isScalar=true)
val EBq = Unit("1.0/s", "Exabecquerel", "activity (of a radionuclide)", 1e+18, isScalar=true)
val Elm = Unit("cd", "Exalumen", "luminous flux", 1e+18, isScalar=true)
val Elx = Unit("cd/m^2", "Exalux", "illuminance", 1e+18, isScalar=true)
val EeV = Unit("gm^2/s^2", "Exaelectron Volts", "measure of energy", 1e+18*1.60217648740e-19, isScalar=true)
val Ely = Unit("m", "Exalightyear", "measure of distance", 1e+18*3600*24*365.25*299792458)
val Epc = Unit("m", "Exaparsec", "measure of distance", 1e+18*3.086e16, isScalar=true)
val EL = Unit("m^3", "Exalitre", "measure of volume", 1e+18/1000, isScalar=true)
