package com.thepyprogrammer.phykt.unit

val fm = Unit("m", "femtometre", "length", 1e-15)
val fs = Unit("s", "femtosecond", "time", 1e-15, isScalar=true)
val fg = Unit("g", "femtogram", "mass", 1e-15/1000, isScalar=true)
val fA = Unit("A", "femtoampere", "electric current", 1e-15, isScalar=true)
val fK = Unit("K", "femtokelvin", "thermodynamic temperature", 1e-15, isScalar=true)
val fmol = Unit("mol", "femtomole", "amount of substance", 1e-15, isScalar=true)
val fcd = Unit("cd", "femtocandela", "luminous intensity", 1e-15, isScalar=true)
val fHz = Unit("1.0/s", "femtohertz", "frequency", 1e-15, isScalar=true)
val fN = Unit("gm/s^2", "femtonewton", "force", 1e-15)
val fPa = Unit("g/ms^2", "femtopascal", "pressure, stress", 1e-15, isScalar=true)
val fJ = Unit("gm^2/s^2", "femtojoule", "energy, work, amount of heat", 1e-15, isScalar=true)
val fW = Unit("gm^2/s^3", "femtowatt", "power, radiant flux", 1e-15, isScalar=true)
val fC = Unit("As", "femtocoulomb", "electric charge, quantity of electricity", 1e-15, isScalar=true)
val fV = Unit("gm^2/As^3", "femtovolt", "electric potential, emf", 1e-15, isScalar=true)
val fΩ = Unit("gm^2/s^3A^2", "femtoohm", "electric resistance, impedance", 1e-15, isScalar=true)
val fohm = Unit("gm^2/s^3A^2", "femtoohm", "electric resistance, impedance", 1e-15, isScalar=true)
val fkat = Unit("mol/s", "femtokatal", "catalytic activity", 1e-15, isScalar=true)
val fS = Unit("A^2s^3/gm^2", "femtosiemen", "electric conductance", 1e-15, isScalar=true)
val fF = Unit("A^2s^4/gm^2", "femtofarad", "capacitance", 1e-15, isScalar=true)
val fWb = Unit("gm^2/As^2", "femtoweber", "magnetic flux", 1e-15, isScalar=true)
val fT = Unit("g/As^2", "femtotesla", "magnetic field", 1e-15)
val fH = Unit("gm^2/A^2s^2", "femtohenry", "inductance", 1e-15, isScalar=true)
val fdegreeCelsius = Unit("K", "femto°Celsius", "temperature on the celsius scale", 1e-15, -273.15, isScalar=true)
val fdegCelsius = Unit("K", "femto°Celsius", "temperature on the celsius scale", 1e-15, -273.15, isScalar=true)
val fdegC = Unit("K", "femto°Celsius", "temperature on the celsius scale", 1e-15, -273.15, isScalar=true)
val fGy = Unit("m^2/s^2", "femtogray", "absorbed dose, specific energy", 1e-15, isScalar=true)
val fSv = Unit("m^2/s^2", "femtosievert", "dose equivalent(d)", 1e-15, isScalar=true)
val fBq = Unit("1.0/s", "femtobecquerel", "activity (of a radionuclide)", 1e-15, isScalar=true)
val flm = Unit("cd", "femtolumen", "luminous flux", 1e-15, isScalar=true)
val flx = Unit("cd/m^2", "femtolux", "illuminance", 1e-15, isScalar=true)
val feV = Unit("gm^2/s^2", "femtoelectron Volts", "measure of energy", 1e-15*1.60217648740e-19, isScalar=true)
val fly = Unit("m", "femtolightyear", "measure of distance", 1e-15*3600*24*365.25*299792458)
val fpc = Unit("m", "femtoparsec", "measure of distance", 1e-15*3.086e16, isScalar=true)
val fL = Unit("m^3", "femtolitre", "measure of volume", 1e-15/1000, isScalar=true)