package com.thepyprogrammer.phykt.unit

val hm = Unit("m", "hectometre", "length", 100.0)
val hs = Unit("s", "hectosecond", "time", 100.0, isScalar=true)
val hg = Unit("g", "hectogram", "mass", 0.1, isScalar=true)
val hA = Unit("A", "hectoampere", "electric current", 100.0, isScalar=true)
val hK = Unit("K", "hectokelvin", "thermodynamic temperature", 100.0, isScalar=true)
val hmol = Unit("mol", "hectomole", "amount of substance", 100.0, isScalar=true)
val hcd = Unit("cd", "hectocandela", "luminous intensity", 100.0, isScalar=true)
val hHz = Unit("1.0/s", "hectohertz", "frequency", 100.0, isScalar=true)
val hN = Unit("gm/s^2", "hectonewton", "force", 100.0)
val hPa = Unit("g/ms^2", "hectopascal", "pressure, stress", 100.0, isScalar=true)
val hJ = Unit("gm^2/s^2", "hectojoule", "energy, work, amount of heat", 100.0, isScalar=true)
val hW = Unit("gm^2/s^3", "hectowatt", "power, radiant flux", 100.0, isScalar=true)
val hC = Unit("As", "hectocoulomb", "electric charge, quantity of electricity", 100.0, isScalar=true)
val hV = Unit("gm^2/As^3", "hectovolt", "electric potential, emf", 100.0, isScalar=true)
val hΩ = Unit("gm^2/s^3A^2", "hectoohm", "electric resistance, impedance", 100.0, isScalar=true)
val hohm = Unit("gm^2/s^3A^2", "hectoohm", "electric resistance, impedance", 100.0, isScalar=true)
val hkat = Unit("mol/s", "hectokatal", "catalytic activity", 100.0, isScalar=true)
val hS = Unit("A^2s^3/gm^2", "hectosiemen", "electric conductance", 100.0, isScalar=true)
val hF = Unit("A^2s^4/gm^2", "hectofarad", "capacitance", 100.0, isScalar=true)
val hWb = Unit("gm^2/As^2", "hectoweber", "magnetic flux", 100.0, isScalar=true)
val hT = Unit("g/As^2", "hectotesla", "magnetic field", 100.0)
val hH = Unit("gm^2/A^2s^2", "hectohenry", "inductance", 100.0, isScalar=true)
val hdegreeCelsius = Unit("K", "hecto°Celsius", "temperature on the celsius scale", 100.0, -273.15, isScalar=true)
val hdegCelsius = Unit("K", "hecto°Celsius", "temperature on the celsius scale", 100.0, -273.15, isScalar=true)
val hdegC = Unit("K", "hecto°Celsius", "temperature on the celsius scale", 100.0, -273.15, isScalar=true)
val hGy = Unit("m^2/s^2", "hectogray", "absorbed dose, specific energy", 100.0, isScalar=true)
val hSv = Unit("m^2/s^2", "hectosievert", "dose equivalent(d)", 100.0, isScalar=true)
val hBq = Unit("1.0/s", "hectobecquerel", "activity (of a radionuclide)", 100.0, isScalar=true)
val hlm = Unit("cd", "hectolumen", "luminous flux", 100.0, isScalar=true)
val hlx = Unit("cd/m^2", "hectolux", "illuminance", 100.0, isScalar=true)
val heV = Unit("gm^2/s^2", "hectoelectron Volts", "measure of energy", 100.0*1.60217648740e-19, isScalar=true)
val hly = Unit("m", "hectolightyear", "measure of distance", 100.0*3600*24*365.25*299792458)
val hpc = Unit("m", "hectoparsec", "measure of distance", 100.0*3.086e16, isScalar=true)
val hL = Unit("m^3", "hectolitre", "measure of volume", 100.0/1000, isScalar=true)