package com.thepyprogrammer.phykt.unit

val km = Unit("m", "kilometre", "length", 1000.0)
val ks = Unit("s", "kilosecond", "time", 1000.0, isScalar=true)
val kg = Unit("g", "kilogram", "mass", isScalar=true)
val kA = Unit("A", "kiloampere", "electric current", 1000.0, isScalar=true)
val kK = Unit("K", "kilokelvin", "thermodynamic temperature", 1000.0, isScalar=true)
val kmol = Unit("mol", "kilomole", "amount of substance", 1000.0, isScalar=true)
val kcd = Unit("cd", "kilocandela", "luminous intensity", 1000.0, isScalar=true)
val kHz = Unit("1.0/s", "kilohertz", "frequency", 1000.0, isScalar=true)
val kN = Unit("gm/s^2", "kilonewton", "force", 1000.0)
val kPa = Unit("g/ms^2", "kilopascal", "pressure, stress", 1000.0, isScalar=true)
val kJ = Unit("gm^2/s^2", "kilojoule", "energy, work, amount of heat", 1000.0, isScalar=true)
val kW = Unit("gm^2/s^3", "kilowatt", "power, radiant flux", 1000.0, isScalar=true)
val kC = Unit("As", "kilocoulomb", "electric charge, quantity of electricity", 1000.0, isScalar=true)
val kV = Unit("gm^2/As^3", "kilovolt", "electric potential, emf", 1000.0, isScalar=true)
val kΩ = Unit("gm^2/s^3A^2", "kiloohm", "electric resistance, impedance", 1000.0, isScalar=true)
val kohm = Unit("gm^2/s^3A^2", "kiloohm", "electric resistance, impedance", 1000.0, isScalar=true)
val kkat = Unit("mol/s", "kilokatal", "catalytic activity", 1000.0, isScalar=true)
val kS = Unit("A^2s^3/gm^2", "kilosiemen", "electric conductance", 1000.0, isScalar=true)
val kF = Unit("A^2s^4/gm^2", "kilofarad", "capacitance", 1000.0, isScalar=true)
val kWb = Unit("gm^2/As^2", "kiloweber", "magnetic flux", 1000.0, isScalar=true)
val kT = Unit("g/As^2", "kilotesla", "magnetic field", 1000.0)
val kH = Unit("gm^2/A^2s^2", "kilohenry", "inductance", 1000.0, isScalar=true)
val kdegreeCelsius = Unit("K", "kilo°Celsius", "temperature on the celsius scale", 1000.0, -273.15, isScalar=true)
val kdegCelsius = Unit("K", "kilo°Celsius", "temperature on the celsius scale", 1000.0, -273.15, isScalar=true)
val kdegC = Unit("K", "kilo°Celsius", "temperature on the celsius scale", 1000.0, -273.15, isScalar=true)
val kGy = Unit("m^2/s^2", "kilogray", "absorbed dose, specific energy", 1000.0, isScalar=true)
val kSv = Unit("m^2/s^2", "kilosievert", "dose equivalent(d)", 1000.0, isScalar=true)
val kBq = Unit("1.0/s", "kilobecquerel", "activity (of a radionuclide)", 1000.0, isScalar=true)
val klm = Unit("cd", "kilolumen", "luminous flux", 1000.0, isScalar=true)
val klx = Unit("cd/m^2", "kilolux", "illuminance", 1000.0, isScalar=true)
val keV = Unit("gm^2/s^2", "kiloelectron Volts", "measure of energy", 1000.0*1.60217648740e-19, isScalar=true)
val kly = Unit("m", "kilolightyear", "measure of distance", 1000.0*3600*24*365.25*299792458)
val kpc = Unit("m", "kiloparsec", "measure of distance", 1000.0*3.086e16, isScalar=true)
val kL = Unit("m^3", "kilolitre", "measure of volume", 1000.0/1000, isScalar=true)
