package com.thepyprogrammer.phykt.unit

import com.thepyprogrammer.ktlib.math.PI

val μm = Unit("m", "micrometre", "length", 1e-06)
val μs = Unit("s", "microsecond", "time", 1e-06, isScalar=true)
val μg = Unit("g", "microgram", "mass", 1e-06/1000, isScalar=true)
val μA = Unit("A", "microampere", "electric current", 1e-06, isScalar=true)
val μK = Unit("K", "microkelvin", "thermodynamic temperature", 1e-06, isScalar=true)
val μmol = Unit("mol", "micromole", "amount of substance", 1e-06, isScalar=true)
val μcd = Unit("cd", "microcandela", "luminous intensity", 1e-06, isScalar=true)
val μHz = Unit("1.0/s", "microhertz", "frequency", 1e-06, isScalar=true)
val μN = Unit("gm/s^2", "micronewton", "force", 1e-06)
val μPa = Unit("g/ms^2", "micropascal", "pressure, stress", 1e-06, isScalar=true)
val μJ = Unit("gm^2/s^2", "microjoule", "energy, work, amount of heat", 1e-06, isScalar=true)
val μW = Unit("gm^2/s^3", "microwatt", "power, radiant flux", 1e-06, isScalar=true)
val μC = Unit("As", "microcoulomb", "electric charge, quantity of electricity", 1e-06, isScalar=true)
val μV = Unit("gm^2/As^3", "microvolt", "electric potential, emf", 1e-06, isScalar=true)
val μΩ = Unit("gm^2/s^3A^2", "microohm", "electric resistance, impedance", 1e-06, isScalar=true)
val μohm = Unit("gm^2/s^3A^2", "microohm", "electric resistance, impedance", 1e-06, isScalar=true)
val μkat = Unit("mol/s", "microkatal", "catalytic activity", 1e-06, isScalar=true)
val μS = Unit("A^2s^3/gm^2", "microsiemen", "electric conductance", 1e-06, isScalar=true)
val μF = Unit("A^2s^4/gm^2", "microfarad", "capacitance", 1e-06, isScalar=true)
val μWb = Unit("gm^2/As^2", "microweber", "magnetic flux", 1e-06, isScalar=true)
val μT = Unit("g/As^2", "microtesla", "magnetic field", 1e-06)
val μH = Unit("gm^2/A^2s^2", "microhenry", "inductance", 1e-06, isScalar=true)
val μdegreeCelsius = Unit("K", "micro°Celsius", "temperature on the celsius scale", 1e-06, -273.15, isScalar=true)
val μdegCelsius = Unit("K", "micro°Celsius", "temperature on the celsius scale", 1e-06, -273.15, isScalar=true)
val μdegC = Unit("K", "micro°Celsius", "temperature on the celsius scale", 1e-06, -273.15, isScalar=true)
val μGy = Unit("m^2/s^2", "microgray", "absorbed dose, specific energy", 1e-06, isScalar=true)
val μSv = Unit("m^2/s^2", "microsievert", "dose equivalent(d)", 1e-06, isScalar=true)
val μBq = Unit("1.0/s", "microbecquerel", "activity (of a radionuclide)", 1e-06, isScalar=true)
val μlm = Unit("cd", "microlumen", "luminous flux", 1e-06, isScalar=true)
val μlx = Unit("cd/m^2", "microlux", "illuminance", 1e-06, isScalar=true)
val μeV = Unit("gm^2/s^2", "microelectron Volts", "measure of energy", 1e-06*1.60217648740e-19, isScalar=true)
val μly = Unit("m", "microlightyear", "measure of distance", 1e-06*3600*24*365.25*299792458)
val μpc = Unit("m", "microparsec", "measure of distance", 1e-06*3.086e16, isScalar=true)
val μL = Unit("m^3", "microlitre", "measure of volume", 1e-06/1000, isScalar=true)
