package com.thepyprogrammer.phykt.unit

val mm = Unit("m", "millimetre", "length", 0.001)
val ms = Unit("s", "millisecond", "time", 0.001, isScalar=true)
val mg = Unit("g", "milligram", "mass", 0.001/1000, isScalar=true)
val mA = Unit("A", "milliampere", "electric current", 0.001, isScalar=true)
val mK = Unit("K", "millikelvin", "thermodynamic temperature", 0.001, isScalar=true)
val mmol = Unit("mol", "millimole", "amount of substance", 0.001, isScalar=true)
val mcd = Unit("cd", "millicandela", "luminous intensity", 0.001, isScalar=true)
val mHz = Unit("1.0/s", "millihertz", "frequency", 0.001, isScalar=true)
val mN = Unit("gm/s^2", "millinewton", "force", 0.001)
val mPa = Unit("g/ms^2", "millipascal", "pressure, stress", 0.001, isScalar=true)
val mJ = Unit("gm^2/s^2", "millijoule", "energy, work, amount of heat", 0.001, isScalar=true)
val mW = Unit("gm^2/s^3", "milliwatt", "power, radiant flux", 0.001, isScalar=true)
val mC = Unit("As", "millicoulomb", "electric charge, quantity of electricity", 0.001, isScalar=true)
val mV = Unit("gm^2/As^3", "millivolt", "electric potential, emf", 0.001, isScalar=true)
val mΩ = Unit("gm^2/s^3A^2", "milliohm", "electric resistance, impedance", 0.001, isScalar=true)
val mohm = Unit("gm^2/s^3A^2", "milliohm", "electric resistance, impedance", 0.001, isScalar=true)
val mkat = Unit("mol/s", "millikatal", "catalytic activity", 0.001, isScalar=true)
val mS = Unit("A^2s^3/gm^2", "millisiemen", "electric conductance", 0.001, isScalar=true)
val mF = Unit("A^2s^4/gm^2", "millifarad", "capacitance", 0.001, isScalar=true)
val mWb = Unit("gm^2/As^2", "milliweber", "magnetic flux", 0.001, isScalar=true)
val mT = Unit("g/As^2", "millitesla", "magnetic field", 0.001)
val mH = Unit("gm^2/A^2s^2", "millihenry", "inductance", 0.001, isScalar=true)
val mdegreeCelsius = Unit("K", "milli°Celsius", "temperature on the celsius scale", 0.001, -273.15, isScalar=true)
val mdegCelsius = Unit("K", "milli°Celsius", "temperature on the celsius scale", 0.001, -273.15, isScalar=true)
val mdegC = Unit("K", "milli°Celsius", "temperature on the celsius scale", 0.001, -273.15, isScalar=true)
val mGy = Unit("m^2/s^2", "milligray", "absorbed dose, specific energy", 0.001, isScalar=true)
val mSv = Unit("m^2/s^2", "millisievert", "dose equivalent(d)", 0.001, isScalar=true)
val mBq = Unit("1.0/s", "millibecquerel", "activity (of a radionuclide)", 0.001, isScalar=true)
val mlm = Unit("cd", "millilumen", "luminous flux", 0.001, isScalar=true)
val mlx = Unit("cd/m^2", "millilux", "illuminance", 0.001, isScalar=true)
val meV = Unit("gm^2/s^2", "millielectron Volts", "measure of energy", 0.001*1.60217648740e-19, isScalar=true)
val mly = Unit("m", "millilightyear", "measure of distance", 0.001*3600*24*365.25*299792458)
val mpc = Unit("m", "milliparsec", "measure of distance", 0.001*3.086e16, isScalar=true)
val mL = Unit("m^3", "millilitre", "measure of volume", 0.001/1000, isScalar=true)
