package com.thepyprogrammer.phykt.unit

val nm = Unit("m", "nanometre", "length", 1e-09)
val ns = Unit("s", "nanosecond", "time", 1e-09, isScalar=true)
val ng = Unit("g", "nanogram", "mass", 1e-09/1000, isScalar=true)
val nA = Unit("A", "nanoampere", "electric current", 1e-09, isScalar=true)
val nK = Unit("K", "nanokelvin", "thermodynamic temperature", 1e-09, isScalar=true)
val nmol = Unit("mol", "nanomole", "amount of substance", 1e-09, isScalar=true)
val ncd = Unit("cd", "nanocandela", "luminous intensity", 1e-09, isScalar=true)
val nHz = Unit("1.0/s", "nanohertz", "frequency", 1e-09, isScalar=true)
val nN = Unit("gm/s^2", "nanonewton", "force", 1e-09)
val nPa = Unit("g/ms^2", "nanopascal", "pressure, stress", 1e-09, isScalar=true)
val nJ = Unit("gm^2/s^2", "nanojoule", "energy, work, amount of heat", 1e-09, isScalar=true)
val nW = Unit("gm^2/s^3", "nanowatt", "power, radiant flux", 1e-09, isScalar=true)
val nC = Unit("As", "nanocoulomb", "electric charge, quantity of electricity", 1e-09, isScalar=true)
val nV = Unit("gm^2/As^3", "nanovolt", "electric potential, emf", 1e-09, isScalar=true)
val nΩ = Unit("gm^2/s^3A^2", "nanoohm", "electric resistance, impedance", 1e-09, isScalar=true)
val nohm = Unit("gm^2/s^3A^2", "nanoohm", "electric resistance, impedance", 1e-09, isScalar=true)
val nkat = Unit("mol/s", "nanokatal", "catalytic activity", 1e-09, isScalar=true)
val nS = Unit("A^2s^3/gm^2", "nanosiemen", "electric conductance", 1e-09, isScalar=true)
val nF = Unit("A^2s^4/gm^2", "nanofarad", "capacitance", 1e-09, isScalar=true)
val nWb = Unit("gm^2/As^2", "nanoweber", "magnetic flux", 1e-09, isScalar=true)
val nT = Unit("g/As^2", "nanotesla", "magnetic field", 1e-09)
val nH = Unit("gm^2/A^2s^2", "nanohenry", "inductance", 1e-09, isScalar=true)
val ndegreeCelsius = Unit("K", "nano°Celsius", "temperature on the celsius scale", 1e-09, -273.15, isScalar=true)
val ndegCelsius = Unit("K", "nano°Celsius", "temperature on the celsius scale", 1e-09, -273.15, isScalar=true)
val ndegC = Unit("K", "nano°Celsius", "temperature on the celsius scale", 1e-09, -273.15, isScalar=true)
val nGy = Unit("m^2/s^2", "nanogray", "absorbed dose, specific energy", 1e-09, isScalar=true)
val nSv = Unit("m^2/s^2", "nanosievert", "dose equivalent(d)", 1e-09, isScalar=true)
val nBq = Unit("1.0/s", "nanobecquerel", "activity (of a radionuclide)", 1e-09, isScalar=true)
val nlm = Unit("cd", "nanolumen", "luminous flux", 1e-09, isScalar=true)
val nlx = Unit("cd/m^2", "nanolux", "illuminance", 1e-09, isScalar=true)
val neV = Unit("gm^2/s^2", "nanoelectron Volts", "measure of energy", 1e-09*1.60217648740e-19, isScalar=true)
val nly = Unit("m", "nanolightyear", "measure of distance", 1e-09*3600*24*365.25*299792458)
val npc = Unit("m", "nanoparsec", "measure of distance", 1e-09*3.086e16, isScalar=true)
val nL = Unit("m^3", "nanolitre", "measure of volume", 1e-09/1000, isScalar=true)
