package com.thepyprogrammer.phykt.unit

val pm = Unit("m", "picometre", "length", 1e-12)
val ps = Unit("s", "picosecond", "time", 1e-12, isScalar=true)
val pg = Unit("g", "picogram", "mass", 1e-12/1000, isScalar=true)
val pA = Unit("A", "picoampere", "electric current", 1e-12, isScalar=true)
val pK = Unit("K", "picokelvin", "thermodynamic temperature", 1e-12, isScalar=true)
val pmol = Unit("mol", "picomole", "amount of substance", 1e-12, isScalar=true)
val pcd = Unit("cd", "picocandela", "luminous intensity", 1e-12, isScalar=true)
val pHz = Unit("1.0/s", "picohertz", "frequency", 1e-12, isScalar=true)
val pN = Unit("gm/s^2", "piconewton", "force", 1e-12)
val pPa = Unit("g/ms^2", "picopascal", "pressure, stress", 1e-12, isScalar=true)
val pJ = Unit("gm^2/s^2", "picojoule", "energy, work, amount of heat", 1e-12, isScalar=true)
val pW = Unit("gm^2/s^3", "picowatt", "power, radiant flux", 1e-12, isScalar=true)
val pC = Unit("As", "picocoulomb", "electric charge, quantity of electricity", 1e-12, isScalar=true)
val pV = Unit("gm^2/As^3", "picovolt", "electric potential, emf", 1e-12, isScalar=true)
val pΩ = Unit("gm^2/s^3A^2", "picoohm", "electric resistance, impedance", 1e-12, isScalar=true)
val pohm = Unit("gm^2/s^3A^2", "picoohm", "electric resistance, impedance", 1e-12, isScalar=true)
val pkat = Unit("mol/s", "picokatal", "catalytic activity", 1e-12, isScalar=true)
val pS = Unit("A^2s^3/gm^2", "picosiemen", "electric conductance", 1e-12, isScalar=true)
val pF = Unit("A^2s^4/gm^2", "picofarad", "capacitance", 1e-12, isScalar=true)
val pWb = Unit("gm^2/As^2", "picoweber", "magnetic flux", 1e-12, isScalar=true)
val pT = Unit("g/As^2", "picotesla", "magnetic field", 1e-12)
val pH = Unit("gm^2/A^2s^2", "picohenry", "inductance", 1e-12, isScalar=true)
val pdegreeCelsius = Unit("K", "pico°Celsius", "temperature on the celsius scale", 1e-12, -273.15, isScalar=true)
val pdegCelsius = Unit("K", "pico°Celsius", "temperature on the celsius scale", 1e-12, -273.15, isScalar=true)
val pdegC = Unit("K", "pico°Celsius", "temperature on the celsius scale", 1e-12, -273.15, isScalar=true)
val pGy = Unit("m^2/s^2", "picogray", "absorbed dose, specific energy", 1e-12, isScalar=true)
val pSv = Unit("m^2/s^2", "picosievert", "dose equivalent(d)", 1e-12, isScalar=true)
val pBq = Unit("1.0/s", "picobecquerel", "activity (of a radionuclide)", 1e-12, isScalar=true)
val plm = Unit("cd", "picolumen", "luminous flux", 1e-12, isScalar=true)
val plx = Unit("cd/m^2", "picolux", "illuminance", 1e-12, isScalar=true)
val peV = Unit("gm^2/s^2", "picoelectron Volts", "measure of energy", 1e-12*1.60217648740e-19, isScalar=true)
val ply = Unit("m", "picolightyear", "measure of distance", 1e-12*3600*24*365.25*299792458)
val ppc = Unit("m", "picoparsec", "measure of distance", 1e-12*3.086e16, isScalar=true)
val pL = Unit("m^3", "picolitre", "measure of volume", 1e-12/1000, isScalar=true)