package com.thepyprogrammer.phykt.unit

val m = Unit("m", "metre", "length", 1.0)
val s = Unit("s", "second", "time", 1.0, isScalar=true)
val g = Unit("g", "gram", "mass", 1.0/1000, isScalar=true)
val A = Unit("A", "ampere", "electric current", 1.0, isScalar=true)
val K = Unit("K", "kelvin", "thermodynamic temperature", 1.0, isScalar=true)
val mol = Unit("mol", "mole", "amount of substance", 1.0, isScalar=true)
val cd = Unit("cd", "candela", "luminous intensity", 1.0, isScalar=true)
val Hz = Unit("1.0/s", "hertz", "frequency", 1.0, isScalar=true)
val N = Unit("gm/s^2", "newton", "force", 1.0)
val Pa = Unit("g/ms^2", "pascal", "pressure, stress", 1.0, isScalar=true)
val J = Unit("gm^2/s^2", "joule", "energy, work, amount of heat", 1.0, isScalar=true)
val W = Unit("gm^2/s^3", "watt", "power, radiant flux", 1.0, isScalar=true)
val C = Unit("As", "coulomb", "electric charge, quantity of electricity", 1.0, isScalar=true)
val V = Unit("gm^2/As^3", "volt", "electric potential, emf", 1.0, isScalar=true)
val Ω = Unit("gm^2/s^3A^2", "ohm", "electric resistance, impedance", 1.0, isScalar=true)
val ohm = Unit("gm^2/s^3A^2", "ohm", "electric resistance, impedance", 1.0, isScalar=true)
val kat = Unit("mol/s", "katal", "catalytic activity", 1.0, isScalar=true)
val Si = Unit("A^2s^3/gm^2", "siemen", "electric conductance", 1.0, isScalar=true)
val F = Unit("A^2s^4/gm^2", "farad", "capacitance", 1.0, isScalar=true)
val Wb = Unit("gm^2/As^2", "weber", "magnetic flux", 1.0, isScalar=true)
val T = Unit("g/As^2", "tesla", "magnetic field", 1.0)
val H = Unit("gm^2/A^2s^2", "henry", "inductance", 1.0, isScalar=true)
val degreeCelsius = Unit("K", "°Celsius", "temperature on the celsius scale", 1.0, -273.15, isScalar=true)
val degCelsius = Unit("K", "°Celsius", "temperature on the celsius scale", 1.0, -273.15, isScalar=true)
val degC = Unit("K", "°Celsius", "temperature on the celsius scale", 1.0, -273.15, isScalar=true)
val Gy = Unit("m^2/s^2", "gray", "absorbed dose, specific energy", 1.0, isScalar=true)
val Sv = Unit("m^2/s^2", "sievert", "dose equivalent(d)", 1.0, isScalar=true)
val Bq = Unit("1.0/s", "becquerel", "activity (of a radionuclide)", 1.0, isScalar=true)
val lm = Unit("cd", "lumen", "luminous flux", 1.0, isScalar=true)
val lx = Unit("cd/m^2", "lux", "illuminance", 1.0, isScalar=true)
val eV = Unit("gm^2/s^2", "electron Volts", "measure of energy", 1*1.60217648740e-19, isScalar=true)
val ly = Unit("m", "lightyear", "measure of distance", 1*3600*24*365.25*299792458)
val pc = Unit("m", "parsec", "measure of distance", 1*3.086e16, isScalar=true)
val L = Unit("m^3", "litre", "measure of volume", 1.0/1000, isScalar=true)
