package com.thepyprogrammer.phykt.unit

val ym = Unit("m", "yoctometre", "length", 1e-24)
val ys = Unit("s", "yoctosecond", "time", 1e-24, isScalar=true)
val yg = Unit("g", "yoctogram", "mass", 1e-24/100, isScalar=true)
val yA = Unit("A", "yoctoampere", "electric current", 1e-24, isScalar=true)
val yK = Unit("K", "yoctokelvin", "thermodynamic temperature", 1e-24, isScalar=true)
val ymol = Unit("mol", "yoctomole", "amount of substance", 1e-24, isScalar=true)
val ycd = Unit("cd", "yoctocandela", "luminous intensity", 1e-24, isScalar=true)
val yHz = Unit("1.0/s", "yoctohertz", "frequency", 1e-24, isScalar=true)
val yN = Unit("gm/s^2", "yoctonewton", "force", 1e-24)
val yPa = Unit("g/ms^2", "yoctopascal", "pressure, stress", 1e-24, isScalar=true)
val yJ = Unit("gm^2/s^2", "yoctojoule", "energy, work, amount of heat", 1e-24, isScalar=true)
val yW = Unit("gm^2/s^3", "yoctowatt", "power, radiant flux", 1e-24, isScalar=true)
val yC = Unit("As", "yoctocoulomb", "electric charge, quantity of electricity", 1e-24, isScalar=true)
val yV = Unit("gm^2/As^3", "yoctovolt", "electric potential, emf", 1e-24, isScalar=true)
val yΩ = Unit("gm^2/s^3A^2", "yoctoohm", "electric resistance, impedance", 1e-24, isScalar=true)
val yohm = Unit("gm^2/s^3A^2", "yoctoohm", "electric resistance, impedance", 1e-24, isScalar=true)
val ykat = Unit("mol/s", "yoctokatal", "catalytic activity", 1e-24, isScalar=true)
val yS = Unit("A^2s^3/gm^2", "yoctosiemen", "electric conductance", 1e-24, isScalar=true)
val yF = Unit("A^2s^4/gm^2", "yoctofarad", "capacitance", 1e-24, isScalar=true)
val yWb = Unit("gm^2/As^2", "yoctoweber", "magnetic flux", 1e-24, isScalar=true)
val yT = Unit("g/As^2", "yoctotesla", "magnetic field", 1e-24)
val yH = Unit("gm^2/A^2s^2", "yoctohenry", "inductance", 1e-24, isScalar=true)
val ydegreeCelsius = Unit("K", "yocto°Celsius", "temperature on the celsius scale", 1e-24, -273.15, isScalar=true)
val ydegCelsius = Unit("K", "yocto°Celsius", "temperature on the celsius scale", 1e-24, -273.15, isScalar=true)
val ydegC = Unit("K", "yocto°Celsius", "temperature on the celsius scale", 1e-24, -273.15, isScalar=true)
val yGy = Unit("m^2/s^2", "yoctogray", "absorbed dose, specific energy", 1e-24, isScalar=true)
val ySv = Unit("m^2/s^2", "yoctosievert", "dose equivalent(d)", 1e-24, isScalar=true)
val yBq = Unit("1.0/s", "yoctobecquerel", "activity (of a radionuclide)", 1e-24, isScalar=true)
val ylm = Unit("cd", "yoctolumen", "luminous flux", 1e-24, isScalar=true)
val ylx = Unit("cd/m^2", "yoctolux", "illuminance", 1e-24, isScalar=true)
val yeV = Unit("gm^2/s^2", "yoctoelectron Volts", "measure of energy", 1e-24*1.60217648740e-19, isScalar=true)
val yly = Unit("m", "yoctolightyear", "measure of distance", 1e-24*3600*24*365.25*299792458)
val ypc = Unit("m", "yoctoparsec", "measure of distance", 1e-24*3.086e16, isScalar=true)
val yL = Unit("m^3", "yoctolitre", "measure of volume", 1e-24/1000, isScalar=true)