package com.thepyprogrammer.phykt.unit

import com.thepyprogrammer.ktlib.math.PI


val Ym = Unit("m", "Yotametre", "length", 1e+24)
val Ys = Unit("s", "Yotasecond", "time", 1e+24, isScalar=true)
val Yg = Unit("g", "Yotagram", "mass", 1e+24 / 1000, isScalar=true)
val YA = Unit("A", "Yotaampere", "electric current", 1e+24, isScalar=true)
val YK = Unit("K", "Yotakelvin", "thermodynamic temperature", 1e+24, isScalar=true)
val Ymol = Unit("mol", "Yotamole", "amount of substance", 1e+24, isScalar=true)
val Ycd = Unit("cd", "Yotacandela", "luminous intensity", 1e+24, isScalar=true)
val YHz = Unit("1.0/s", "Yotahertz", "frequency", 1e+24, isScalar=true)
val YN = Unit("gm/s^2", "Yotanewton", "force", 1e+24)
val YPa = Unit("g/ms^2", "Yotapascal", "pressure, stress", 1e+24, isScalar=true)
val YJ = Unit("gm^2/s^2", "Yotajoule", "energy, work, amount of heat", 1e+24, isScalar=true)
val YW = Unit("gm^2/s^3", "Yotawatt", "power, radiant flux", 1e+24, isScalar=true)
val YC = Unit("As", "Yotacoulomb", "electric charge, quantity of electricity", 1e+24, isScalar=true)
val YV = Unit("gm^2/As^3", "Yotavolt", "electric potential, emf", 1e+24, isScalar=true)
val YΩ = Unit("gm^2/s^3A^2", "Yotaohm", "electric resistance, impedance", 1e+24, isScalar=true)
val Yohm = Unit("gm^2/s^3A^2", "Yotaohm", "electric resistance, impedance", 1e+24, isScalar=true)
val Ykat = Unit("mol/s", "Yotakatal", "catalytic activity", 1e+24, isScalar=true)
val YS = Unit("A^2s^3/gm^2", "Yotasiemen", "electric conductance", 1e+24, isScalar=true)
val YF = Unit("A^2s^4/gm^2", "Yotafarad", "capacitance", 1e+24, isScalar=true)
val YWb = Unit("gm^2/As^2", "Yotaweber", "magnetic flux", 1e+24, isScalar=true)
val YT = Unit("g/As^2", "Yotatesla", "magnetic field", 1e+24)
val YH = Unit("gm^2/A^2s^2", "Yotahenry", "inductance", 1e+24, isScalar=true)
val YdegreeCelsius = Unit("K", "Yota°Celsius", "temperature on the celsius scale", 1e+24, -273.15, isScalar=true)
val YdegCelsius = Unit("K", "Yota°Celsius", "temperature on the celsius scale", 1e+24, -273.15, isScalar=true)
val YdegC = Unit("K", "Yota°Celsius", "temperature on the celsius scale", 1e+24, -273.15, isScalar=true)
val YGy = Unit("m^2/s^2", "Yotagray", "absorbed dose, specific energy", 1e+24, isScalar=true)
val YSv = Unit("m^2/s^2", "Yotasievert", "dose equivalent(d)", 1e+24, isScalar=true)
val YBq = Unit("1.0/s", "Yotabecquerel", "activity (of a radionuclide)", 1e+24, isScalar=true)
val Ylm = Unit("cd", "Yotalumen", "luminous flux", 1e+24, isScalar=true)
val Ylx = Unit("cd/m^2", "Yotalux", "illuminance", 1e+24, isScalar=true)
val YeV = Unit("gm^2/s^2", "Yotaelectron Volts", "measure of energy", 1e+24*1.60217648740e-19, isScalar=true)
val Yly = Unit("m", "Yotalightyear", "measure of distance", 1e+24*3600*24*365.25*299792458)
val Ypc = Unit("m", "Yotaparsec", "measure of distance", 1e+24*3.086e16, isScalar=true)
val YL = Unit("m^3", "Yotalitre", "measure of volume", 1e+24/1000, isScalar=true)