package com.thepyprogrammer.phykt.unit

val zm = Unit("m", "zeptometre", "length", 1e-21)
val zs = Unit("s", "zeptosecond", "time", 1e-21, isScalar=true)
val zg = Unit("g", "zeptogram", "mass", 1e-21/1000, isScalar=true)
val zA = Unit("A", "zeptoampere", "electric current", 1e-21, isScalar=true)
val zK = Unit("K", "zeptokelvin", "thermodynamic temperature", 1e-21, isScalar=true)
val zmol = Unit("mol", "zeptomole", "amount of substance", 1e-21, isScalar=true)
val zcd = Unit("cd", "zeptocandela", "luminous intensity", 1e-21, isScalar=true)
val zHz = Unit("1.0/s", "zeptohertz", "frequency", 1e-21, isScalar=true)
val zN = Unit("gm/s^2", "zeptonewton", "force", 1e-21)
val zPa = Unit("g/ms^2", "zeptopascal", "pressure, stress", 1e-21, isScalar=true)
val zJ = Unit("gm^2/s^2", "zeptojoule", "energy, work, amount of heat", 1e-21, isScalar=true)
val zW = Unit("gm^2/s^3", "zeptowatt", "power, radiant flux", 1e-21, isScalar=true)
val zC = Unit("As", "zeptocoulomb", "electric charge, quantity of electricity", 1e-21, isScalar=true)
val zV = Unit("gm^2/As^3", "zeptovolt", "electric potential, emf", 1e-21, isScalar=true)
val zΩ = Unit("gm^2/s^3A^2", "zeptoohm", "electric resistance, impedance", 1e-21, isScalar=true)
val zohm = Unit("gm^2/s^3A^2", "zeptoohm", "electric resistance, impedance", 1e-21, isScalar=true)
val zkat = Unit("mol/s", "zeptokatal", "catalytic activity", 1e-21, isScalar=true)
val zS = Unit("A^2s^3/gm^2", "zeptosiemen", "electric conductance", 1e-21, isScalar=true)
val zF = Unit("A^2s^4/gm^2", "zeptofarad", "capacitance", 1e-21, isScalar=true)
val zWb = Unit("gm^2/As^2", "zeptoweber", "magnetic flux", 1e-21, isScalar=true)
val zT = Unit("g/As^2", "zeptotesla", "magnetic field", 1e-21)
val zH = Unit("gm^2/A^2s^2", "zeptohenry", "inductance", 1e-21, isScalar=true)
val zdegreeCelsius = Unit("K", "zepto°Celsius", "temperature on the celsius scale", 1e-21, -273.15, isScalar=true)
val zdegCelsius = Unit("K", "zepto°Celsius", "temperature on the celsius scale", 1e-21, -273.15, isScalar=true)
val zdegC = Unit("K", "zepto°Celsius", "temperature on the celsius scale", 1e-21, -273.15, isScalar=true)
val zGy = Unit("m^2/s^2", "zeptogray", "absorbed dose, specific energy", 1e-21, isScalar=true)
val zSv = Unit("m^2/s^2", "zeptosievert", "dose equivalent(d)", 1e-21, isScalar=true)
val zBq = Unit("1.0/s", "zeptobecquerel", "activity (of a radionuclide)", 1e-21, isScalar=true)
val zlm = Unit("cd", "zeptolumen", "luminous flux", 1e-21, isScalar=true)
val zlx = Unit("cd/m^2", "zeptolux", "illuminance", 1e-21, isScalar=true)
val zeV = Unit("gm^2/s^2", "zeptoelectron Volts", "measure of energy", 1e-21*1.60217648740e-19, isScalar=true)
val zly = Unit("m", "zeptolightyear", "measure of distance", 1e-21*3600*24*365.25*299792458)
val zpc = Unit("m", "zeptoparsec", "measure of distance", 1e-21*3.086e16, isScalar=true)
val zL = Unit("m^3", "zeptolitre", "measure of volume", 1e-21/1000, isScalar=true)