package com.thepyprogrammer.phykt.unit

import com.thepyprogrammer.ktlib.math.PI

val Zm = Unit("m", "Zetametre", "length", 1e+21)
val Zs = Unit("s", "Zetasecond", "time", 1e+21, isScalar=true)
val Zg = Unit("g", "Zetagram", "mass", 1e+21/1000, isScalar=true)
val ZA = Unit("A", "Zetaampere", "electric current", 1e+21, isScalar=true)
val ZK = Unit("K", "Zetakelvin", "thermodynamic temperature", 1e+21, isScalar=true)
val Zmol = Unit("mol", "Zetamole", "amount of substance", 1e+21, isScalar=true)
val Zcd = Unit("cd", "Zetacandela", "luminous intensity", 1e+21, isScalar=true)
val ZHz = Unit("1.0/s", "Zetahertz", "frequency", 1e+21, isScalar=true)
val ZN = Unit("gm/s^2", "Zetanewton", "force", 1e+21)
val ZPa = Unit("g/ms^2", "Zetapascal", "pressure, stress", 1e+21, isScalar=true)
val ZJ = Unit("gm^2/s^2", "Zetajoule", "energy, work, amount of heat", 1e+21, isScalar=true)
val ZW = Unit("gm^2/s^3", "Zetawatt", "power, radiant flux", 1e+21, isScalar=true)
val ZC = Unit("As", "Zetacoulomb", "electric charge, quantity of electricity", 1e+21, isScalar=true)
val ZV = Unit("gm^2/As^3", "Zetavolt", "electric potential, emf", 1e+21, isScalar=true)
val ZΩ = Unit("gm^2/s^3A^2", "Zetaohm", "electric resistance, impedance", 1e+21, isScalar=true)
val Zohm = Unit("gm^2/s^3A^2", "Zetaohm", "electric resistance, impedance", 1e+21, isScalar=true)
val Zkat = Unit("mol/s", "Zetakatal", "catalytic activity", 1e+21, isScalar=true)
val ZS = Unit("A^2s^3/gm^2", "Zetasiemen", "electric conductance", 1e+21, isScalar=true)
val ZF = Unit("A^2s^4/gm^2", "Zetafarad", "capacitance", 1e+21, isScalar=true)
val ZWb = Unit("gm^2/As^2", "Zetaweber", "magnetic flux", 1e+21, isScalar=true)
val ZT = Unit("g/As^2", "Zetatesla", "magnetic field", 1e+21)
val ZH = Unit("gm^2/A^2s^2", "Zetahenry", "inductance", 1e+21, isScalar=true)
val ZdegreeCelsius = Unit("K", "Zeta°Celsius", "temperature on the celsius scale", 1e+21, -273.15, isScalar=true)
val ZdegCelsius = Unit("K", "Zeta°Celsius", "temperature on the celsius scale", 1e+21, -273.15, isScalar=true)
val ZdegC = Unit("K", "Zeta°Celsius", "temperature on the celsius scale", 1e+21, -273.15, isScalar=true)
val ZGy = Unit("m^2/s^2", "Zetagray", "absorbed dose, specific energy", 1e+21, isScalar=true)
val ZSv = Unit("m^2/s^2", "Zetasievert", "dose equivalent(d)", 1e+21, isScalar=true)
val ZBq = Unit("1.0/s", "Zetabecquerel", "activity (of a radionuclide)", 1e+21, isScalar=true)
val Zlm = Unit("cd", "Zetalumen", "luminous flux", 1e+21, isScalar=true)
val Zlx = Unit("cd/m^2", "Zetalux", "illuminance", 1e+21, isScalar=true)
val ZeV = Unit("gm^2/s^2", "Zetaelectron Volts", "measure of energy", 1e+21*1.60217648740e-19, isScalar=true)
val Zly = Unit("m", "Zetalightyear", "measure of distance", 1e+21*3600*24*365.25*299792458)
val Zpc = Unit("m", "Zetaparsec", "measure of distance", 1e+21*3.086e16, isScalar=true)
val ZL = Unit("m^3", "Zetalitre", "measure of volume", 1e+21/1000, isScalar=true)
